worker_processes auto;
events { worker_connections 4096; }

http {
  include /etc/nginx/limits/rate.conf;
  include /etc/nginx/limits/conn.conf;
  log_format flowjson escape=json '{'
    '"ts_start":$time_iso8601,'
    '"remote_addr":"$remote_addr",'
    '"connection":$connection,'
    '"request":"$request",'
    '"status":$status,'
    '"bytes_sent":$body_bytes_sent,'
    '"request_length":$request_length,'
    '"request_time":$request_time'
  '}';
  access_log /var/log/nginx/flow.log flowjson;

  client_body_timeout 10s;
  client_header_timeout 10s;
  send_timeout 10s;
  client_max_body_size 1m;
  client_body_buffer_size 16k;

  upstream backend { server backend:80; }
  server {
    listen 80;
    # limit_req/limit_conn written by Module 4
    location / {
      proxy_pass http://backend;
      proxy_http_version 1.1;
      proxy_set_header Connection "";
      proxy_buffering off;
      proxy_request_buffering off;
    }
  }
}
